### ISSUE TITLE
How do I calculate LRP metric for test set from custom dataset?

### ISSUE THREAD

**Issue by priteshgohil** [cancam/LRP#6]
I have my own dataset collected from the University. How do I calculate LRP for this dataset?

**Comment by cancam** [comment]
Hi @priteshgohil ,
If your annotations and detection outputs follow the same format as COCO dataset you can use COCO API if not, you can follow the official instructions by following this link: http://cocodataset.org/#format-data.

If you decide to follow COCO format, you should change the following lines to evaluate detection outputs under LRP.
https://github.com/cancam/LRP/blob/de7bae3887211a605d367c71643a76789384669c/cocoLRPapi-master/PythonAPI/evalDemoLRP.py#L8
https://github.com/cancam/LRP/blob/de7bae3887211a605d367c71643a76789384669c/cocoLRPapi-master/PythonAPI/evalDemoLRP.py#L11

Additionally, if you prefer to implement LRP on your own, please check the pseudo code below:
```
for s in range(0,1,0.01):
  Threshold detection set from s
  Match thresholded detections with ground truths 
  According to this matching identify  TP, FP FN numbers anda IoUs of the confidence scores
  Use Eq 5 to find LRP of this thresholded set (or Eq 1-4 LRP and the components.)
endfor
return the minimum LRP value as the oLRP
```
Note that more efficient implementations can be used (such as instead of matching every step, you can match once - please check evaluateImg.py and accumulate.py in cocoevalLRP.py for details)  but this pseudocode presents the basic steps.

I'm closing this issue, if you have further questions please feel free the reopen it.
Baris.
